[SCRUM-50] ErrorFeature: 네트워크 에러뷰, 서버통신 에러뷰 UI
Nexters/Mohanyang-iOS pull request #57
Opened 2024-11-14 15:19 UTC by Jihyun247

## [SCRUM-50] FEAT : ErrorFeature & 네트워크 에러뷰, 서버통신 에러뷰 UI

## 무엇에 관한 PR 인가요? 🙋
두 에러 뷰 UI

## 어떤 것을 작업하셨나요? 🛠
- ErrorFeature 모듈 생성
- 두 에러 뷰 UI
- Example app

## 🌱 PR Point
- 피알 포인트는 아니고 ... 고새 몇달 스유 안했다고 또 살짝 가물가물 해졌네요 , ,

2024-11-15 02:55 UTC, devMinseok requested changes
고생했어!

2024-11-15 02:55 UTC, devMinseok commented on Projects/Feature/CatFeature/Project.swift
> +      .dependency(module: Feature.ErrorFeature)
ErrorFeature는 Feature모듈의 의존성에 추가하고 AppView.swift에다가 띄우는식으로 하면어떨까?

```swift
public struct AppView: View {
  let store: StoreOf<AppCore>
  
  public init(store: StoreOf<AppCore>) {
    self.store = store
  }
  
  public var body: some View {
    Group {
         .....
    }
    .transition(.opacity)
    .animation(.easeInOut, value: store.home == nil)
    .onLoad {
      store.send(.onLoad)
    }
    .fullScreenCover(errorPresented) {
        // 에러화면띄우기
    }
  }
}
```

2024-11-23 18:39 UTC, Jihyun247 commented
남은 task
- [ ] ErrorFeature Core 구현 (재시도 버튼, 홈으로 이동, 문의 이동)
- [ ] '이름 수정', '내 고양이 변경' api 에 스트림 연결 ('고양이 불러오기'는 테스트로 연결된 상태)

좀 더 고민해볼 점
- ErrorFeature에서 재시도 버튼 action 발생 시 이후 처리를 어떻게 해야할지

2024-11-24 03:59 UTC, devMinseok commented on Projects/Feature/Feature/Sources/AppView.swift
> +    }
LoadingView를 따로 분리해서 만들어서 사용하는게 좋을거 같네

2024-11-24 03:59 UTC, devMinseok commented on Projects/Feature/Feature/Sources/AppView.swift
> +      // transaction으로 로딩뷰만 애니메이션을 disable하고싶은데 잘 안됨
다른 View 컴포넌트도 같이 애니메이션되어서 그런걸까?
아래 처럼 일단 애니메이션을 없애는 방법도 참고해줘
`.animation(nil, value: UUID())`

2024-11-24 03:59 UTC, devMinseok commented on Projects/Core/StreamListener/Interface/StreamListenerInterface.swift
> +  public var updateServerState: @Sendable () -> AsyncStream<ServerState> = { .never }
목적에 종속되지 않도록 만드는게 좋을거 같아
**Key**(네트워크 에러 리스너)와 **value**(에러타입) 쌍으로 이루어진 배열을 갖게해서 (DIContainer 구현 방법 처럼)
send할때 key값과 value를 주고 receive 할때 key값을 넘겨서 그 key의 value만 옵저빙 하도록

2024-11-24 03:59 UTC, devMinseok commented on Projects/Core/StreamListener/Interface/StreamListenerInterface.swift
> +  public var updateServerState: @Sendable () -> AsyncStream<ServerState> = { .never }
이런식으로 해야 앞으로 개선해야하는 토스트 메시지, 네트워크 오프라인 유무 등에도 적용하기 좋을거 같네

2024-11-24 04:19 UTC, devMinseok submitted a review, later dismissed

2024-11-24 06:12 UTC, Jihyun247 commented on Projects/Feature/Feature/Sources/AppView.swift
> +    }
엉 안그래도 빼야겠다 생각은 했는데 로딩뷰를 대체 어느 모듈에 둬야할지 고민중 @.@
로딩뷰는 걍 Feature 모듈에 두는거 어때

2024-11-24 06:30 UTC, devMinseok commented on Projects/Feature/Feature/Sources/AppView.swift
> +    }
어 그래도 괜찮을거 같아!

2024-11-24 08:25 UTC, Jihyun247 commented
남은 task

- [ ] 네트워크 연결 유실 시 재시도 처리 (현재는 아무 동작 안하고 에러뷰만 dismiss)
- [ ] 서버통신 에러 시 홈으로 이동 -> (온보딩에서 서버통신 에러가 나고 '홈으로 이동'을 누르면 온보딩 첫페이지로 이동해야함 -> 이때 온보딩 carousel 이미지들이 안뜨는 이슈)

리팩토링
- [ ] 민석 코멘트 반영해서 스트림리스너 리팩토링
- [ ] network 연결 유실 시 리퀘스트-리스폰스로 네트워크연결유실을 캐치하는 것은 너무 오래걸림. NetworkTracking 모듈을 사용하는 방법 고민 중 ... ... ..

2024-11-24 08:37 UTC, devMinseok approved these changes

2024-11-24 08:37 UTC, merged